import type { Metadata } from "next";
import "@/assets/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/layout/header/header";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import {getLocale, setRequestLocale} from 'next-intl/server';
import { Footer } from "@/components/layout/footer/footer";
 
type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};
 
export default async function LocaleLayout({children, params}: Props) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

 setRequestLocale(locale);

 
  return (
    <>
      <html  lang={locale} suppressHydrationWarning>
        <head />
        <body className="overflow-x-hidden">
          <NextIntlClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              <main className="pt-[57px]">
                {children}
              </main>
            </ThemeProvider>
            <Footer/>
          </NextIntlClientProvider>
          

        </body>
      </html>
    </>
  )
}




